### ISSUE TITLE
Indexer Event Filtering by type issue

### ISSUE THREAD

**Issue by feedkeek** [movementlabsxyz/movement#809]
**Describe the bug**
When querying `Events` by `type` request return an error.

**To Reproduce**
1. Execute the following GraphQL query:
```
query MyQuery {
  events(
    where: {type: {_eq: "0x925727048db3c333f97459bc00bd574c0404ac55db7c3e1d9f442b31f4137c58::domains::RegisterNameEvent"}}
  ) {
    account_address
    creation_number
    data
    event_index
    indexed_type
    inserted_at
    sequence_number
    transaction_block_height
    transaction_version
    type
  }
}
```
2. Observe the errored response:
```
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at fetch (https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:203246)\n    at https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:197788\n    at Generator.next (<anonymous>)\n    at s (https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:196790)\n    at https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:196751\n    at new Promise (<anonymous>)\n    at i.<computed>.r.<computed> [as next] (https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:196703)\n    at https://cloud.hasura.io/public-graphiql/static/js/main.1dbb5e19.js:2:161135"
    }
  ]
}
```

**Expected behavior**
The query should return filtered events without error.

**Comment by dio-dev** [comment]
@0xPrimata Hey we still facing this issue, any updates on it?

**Comment by vscorpio** [comment]
```
query MyQuery {
  events(
    where: {
      indexed_type: {_regex: "^0xe577b40d9348496fe1f71783e0c3fc719ed05333f74c4e3d95d7688ca5b7df74::swap::SwapEvent"},
			data: {
        _contains: {
          user: "0xbd9162ee6441fcf49652f0a50706279187e744aa4622a7c30bfeeaa18b7e4147"
        }
      }
    },
    limit: 1
  ) {
    account_address
    creation_number
    data
    event_index
    indexed_type
    inserted_at
    sequence_number
    transaction_block_height
    transaction_version
    type
  }
}
```

This also fails and a bunch of other queries like this either fail, or take 1 minute to load.
